[metadata]
name = runstarnet
version = attr: runstarnet.__version__
author = Keith Gorlen
author_email = kgorlen@gmail.com
description = Run StarNet++ from Lightroom Classic.
long_description = file: README.md, LICENSE.txt
url = https://github.com/kgorlen/runstarnet
keywords = StarNet, Star Removal, Lightroom Classic, Python
license_expression = MIT
classifiers = 
    Programming Language :: Python :: 3.12
    Operating System :: OS Independent
[options]
include_package_data = True
package_dir=
    =src
packages = find:
python_requires = >=3.12
install_requires =
    build

[options.packages.find]
where=src

[options.entry_points]
console_scripts =
    runstarnet = runstarnet.runstarnet:cli
